/*
DECLARE
    LV_STATE_TXT BB_BASKET.SHIPSTATE%TYPE;
    LV_SUB_NUM BB_BASKET.SUBTOTAL%TYPE;
    LV_TAX_NUM NUMBER(4,2) := 0;
BEGIN
    SELECT SUBTOTAL, SHIPSTATE
        INTO LV_SUB_NUM, LV_STATE_TXT
        FROM BB_BASKET
            WHERE IDBASKET = 4;
    IF LV_STATE_TXT = 'VA' THEN
        LV_TAX_NUM := LV_SUB_NUM * 0.6;
    ELSIF LV_STATE_TXT = 'ME' THEN
        LV_TAX_NUM := LV_SUB_NUM * 0.5;
    ELSIF LV_STATE_TXT = 'NY' THEN
        LV_TAX_NUM := LV_SUB_NUM * 0.7;
    ELSE
        LV_TAX_NUM := LV_SUB_NUM * 0.4;
    END IF;
    DBMS_OUTPUT.PUT_LINE('ST: ' || LV_STATE_TXT || ' Sub: ' || LV_SUB_NUM || ' Tax: ' || LV_TAX_NUM);
END;
*/

/*
DECLARE
    LV_FIRST_TXT BB_SHOPPER.FIRSTNAME%TYPE := 'Jeffrey';
    LV_LAST_TXT BB_SHOPPER.LASTNAME%TYPE := 'Brand';
    LV_EMAIL_TXT BB_SHOPPER.EMAIL%TYPE := 'jbrand@site.com';
BEGIN
    INSERT INTO BB_SHOPPER (IDSHOPPER, FIRSTNAME, LASTNAME, EMAIL)
    VALUES (BB_SHOPPER_SEQ.NEXTVAL, LV_FIRST_TXT, LV_LAST_TXT, LV_EMAIL_TXT);
    COMMIT;
END;

SELECT * FROM BB_SHOPPER;
*/

/*
DECLARE
    REC_SHOPPER BB_SHOPPER%ROWTYPE;
BEGIN
    SELECT *
    INTO REC_SHOPPER
    FROM BB_SHOPPER
    WHERE IDSHOPPER = 25;
    DBMS_OUTPUT.PUT_LINE(REC_SHOPPER.LASTNAME);
    DBMS_OUTPUT.PUT_LINE(REC_SHOPPER.ADDRESS);
    DBMS_OUTPUT.PUT_LINE(REC_SHOPPER.EMAIL);
END;
*/

